---
version: '3'
services:
  netbox:
    build:
      context: ../
      dockerfile: development/Dockerfile
    image: "vrf-context-plugin/netbox:${NETBOX_VER}-py${PYTHON_VER}"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../:/source
    tty: true
  worker:
    build:
      context: ../
      dockerfile: development/Dockerfile
    image: "vrf-context-plugin/netbox:${NETBOX_VER}-py${PYTHON_VER}"
    command: sh -c "python manage.py rqworker"
    depends_on:
      - netbox
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../vrf_context:/source/vrf_context
    tty: true
  postgres:
    image: postgres:13.8
    env_file: dev.env
    volumes:
      - pgdata_netbox_onboarding:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: ./dev.env
volumes:
  pgdata_netbox_onboarding:
